export interface DistParam { key: string; label: string; symbol: string; min: number; max: number; step: number; default: number; }
export interface DistConfig { id: string; name: string; regClass: string; tClass: string; formula: string; description: string; isDiscrete: boolean; color: string; shape: string; params: DistParam[]; }

const bell='M3 20Q7 20 8 12Q9 4 12 4Q15 4 16 12Q17 20 21 20';
const flat='M4 8h16M4 8v10M20 8v10';
const decay='M4 8Q6 8 8 10Q10 18 21 20';
const skewR='M4 20Q8 20 8 12Q9 6 12 5Q14 4 17 8Q19 12 21 20';
const uShape='M4 20Q8 20 8 12Q10 4 12 4Q14 4 16 12Q18 20 21 20';
const wavy='M4 12Q7 20 10 8Q13 20 16 8Q19 20 21 12';
const bars='M4 20v-6h3v6M9 20v-10h3v10M14 20v-4h3v4M19 20v-8h3v8';
const decBars='M4 20v-6h3v6M8 20v-12h3v12M12 20v-14h3v14M16 20v-16h3v16M20 20v-10h3v10';

const M  = (k:string,l:string,s:string,min:number,max:number,step:number,d:number):DistParam => ({key:k,label:l,symbol:s,min,max,step,default:d});

export const DISTRIBUTIONS: DistConfig[] = [
  { id:'normal',name:'Normal',regClass:'regulation-card--irl',tClass:'t-irl',formula:'f(x)=\\frac{1}{\\sigma\\sqrt{2\\pi}}e^{-\\frac{(x-\\mu)^2}{2\\sigma^2}}',description:'The bell-shaped Gaussian distribution. Fundamental to statistics; describes sums of independent random variables via the Central Limit Theorem.',isDiscrete:false,color:'#C0622F',shape:bell,params:[M('mean','Mean','\\mu',-5,5,0.1,0),M('std_dev','Std Dev','\\sigma',0.1,5,0.1,1)]},
  { id:'uniform',name:'Uniform',regClass:'regulation-card--lcr',tClass:'t-lcr',formula:'f(x)=\\frac{1}{b-a}\\quad\\text{for }a\\leq x\\leq b',description:'All values in [a, b] are equally likely. Models complete randomness within a bounded interval.',isDiscrete:false,color:'#0D3B66',shape:flat,params:[M('a','Min','a',-2,2,0.1,0),M('b','Max','b',0.1,5,0.1,1)]},
  { id:'lognormal',name:'Log-Normal',regClass:'regulation-card--nsfr',tClass:'t-nsfr',formula:'f(x)=\\frac{1}{x\\sigma\\sqrt{2\\pi}}e^{-\\frac{(\\ln x-\\mu)^2}{2\\sigma^2}}',description:'Distribution of a random variable whose logarithm is normally distributed. Models stock prices, incomes, and biological measurements.',isDiscrete:false,color:'#62A87C',shape:skewR,params:[M('mu','Location','\\mu',-2,2,0.1,0),M('sigma','Scale','\\sigma',0.1,3,0.1,0.5)]},
  { id:'exponential',name:'Exponential',regClass:'regulation-card--nsfr',tClass:'t-nsfr',formula:'f(x)=\\lambda e^{-\\lambda x}\\quad\\text{for }x\\geq 0',description:'Models waiting times between events in a Poisson process. Memoryless property.',isDiscrete:false,color:'#62A87C',shape:decay,params:[M('lambda','Rate','\\lambda',0.1,5,0.1,1.5)]},
  { id:'gamma',name:'Gamma',regClass:'regulation-card--almm',tClass:'t-almm',formula:'f(x)=\\frac{\\beta^{\\alpha}}{\\Gamma(\\alpha)}x^{\\alpha-1}e^{-\\beta x}',description:'Generalizes the exponential distribution. Models waiting times, rainfall, insurance claims.',isDiscrete:false,color:'#7B5EA7',shape:skewR,params:[M('alpha','Shape','\\alpha',0.1,10,0.1,2),M('beta','Rate','\\beta',0.1,5,0.1,2)]},
  { id:'beta',name:'Beta',regClass:'regulation-card--peru',tClass:'t-peru',formula:'f(x)=\\frac{\\Gamma(\\alpha+\\beta)}{\\Gamma(\\alpha)\\Gamma(\\beta)}x^{\\alpha-1}(1-x)^{\\beta-1}',description:'Flexible distribution on [0,1]. Models proportions, probabilities, task completion. Conjugate prior for binomial.',isDiscrete:false,color:'#C2273E',shape:uShape,params:[M('alpha','Alpha','\\alpha',0.1,10,0.1,2),M('beta','Beta','\\beta',0.1,10,0.1,5)]},
  { id:'weibull',name:'Weibull',regClass:'regulation-card--panama',tClass:'t-panama',formula:'f(x)=\\frac{k}{\\lambda}\\left(\\frac{x}{\\lambda}\\right)^{k-1}e^{-(x/\\lambda)^k}',description:'Models lifetime and failure data. Widely used in reliability engineering.',isDiscrete:false,color:'#003087',shape:wavy,params:[M('k','Shape','k',0.1,5,0.1,1.5),M('lambda','Scale','\\lambda',0.1,5,0.1,1)]},
  { id:'studentt',name:"Student's t",regClass:'regulation-card--panama',tClass:'t-panama',formula:'f(x)\\propto\\left(1+\\frac{(x-\\mu)^2}{\\nu\\sigma^2}\\right)^{-(\\nu+1)/2}',description:'Heavier tails than normal. Used for small-sample inference and robust regression.',isDiscrete:false,color:'#003087',shape:bell,params:[M('mu','Location','\\mu',-3,3,0.1,0),M('sigma','Scale','\\sigma',0.1,3,0.1,1),M('nu','DF','\\nu',0.5,30,0.5,3)]},
  { id:'chisquared',name:'Chi-Squared',regClass:'regulation-card--peru',tClass:'t-peru',formula:'f(x)=\\frac{1}{2^{k/2}\\Gamma(k/2)}x^{k/2-1}e^{-x/2}',description:'Sum of k squared independent standard normals. Foundation of goodness-of-fit tests.',isDiscrete:false,color:'#C2273E',shape:skewR,params:[M('k','DF','k',0.5,20,0.5,3)]},
  { id:'fisher',name:'Fisher (F)',regClass:'regulation-card--uk-fra',tClass:'t-uk-fra',formula:'f(x)=\\frac{\\sqrt{\\frac{(d_1x)^{d_1}d_2^{d_2}}{(d_1x+d_2)^{d_1+d_2}}}}{x\\,B(d_1/2,d_2/2)}',description:'Ratio of two independent chi-squared variables. Used in ANOVA and regression testing.',isDiscrete:false,color:'#1E3A8A',shape:skewR,params:[M('d1','DF₁','d_1',1,20,1,4),M('d2','DF₂','d_2',1,30,1,10)]},
  { id:'erlang',name:'Erlang',regClass:'regulation-card--australia-apra',tClass:'t-australia-apra',formula:'f(x)=\\frac{\\lambda^k}{(k-1)!}x^{k-1}e^{-\\lambda x}',description:'Special case of Gamma with integer shape. Waiting time for k-th event in Poisson process.',isDiscrete:false,color:'#006A4E',shape:skewR,params:[M('k','Shape','k',1,20,1,3),M('lambda','Rate','\\lambda',0.1,5,0.1,1)]},
  { id:'poisson',name:'Poisson',regClass:'regulation-card--japan-bsr',tClass:'t-japan-bsr',formula:'P(X=k)=\\frac{\\lambda^k e^{-\\lambda}}{k!}',description:'Counts events at a fixed average rate. Models website hits, decay, call arrivals.',isDiscrete:true,color:'#BC002D',shape:bars,params:[M('lambda','Rate','\\lambda',0.5,15,0.5,4)]},
  { id:'geometric',name:'Geometric',regClass:'regulation-card--singapore-mas',tClass:'t-singapore-mas',formula:'P(X=k)=(1-p)^k p',description:'Failures before first success. Memoryless discrete distribution.',isDiscrete:true,color:'#DF0024',shape:decBars,params:[M('p','Probability','p',0.05,0.95,0.05,0.3)]},
  { id:'binomial',name:'Binomial',regClass:'regulation-card--canada-osfi',tClass:'t-canada-osfi',formula:'P(X=k)=\\binom{n}{k}p^k(1-p)^{n-k}',description:'Successes in n independent Bernoulli trials. Models coin flips, QC sampling, A/B tests.',isDiscrete:true,color:'#D52B1E',shape:bars,params:[M('n','Trials','n',1,50,1,20),M('p','Probability','p',0.05,0.95,0.05,0.5)]},
  { id:'hypergeometric',name:'Hypergeometric',regClass:'regulation-card--switzerland-finma',tClass:'t-switzerland-finma',formula:'P(X=k)=\\frac{\\binom{K}{k}\\binom{N-K}{n-k}}{\\binom{N}{n}}',description:'Successes in n draws without replacement. Models lottery odds, audit sampling.',isDiscrete:true,color:'#DA291C',shape:bars,params:[M('N','Population','N',10,100,5,50),M('K','Successes','K',1,100,1,20),M('n','Draws','n',1,50,1,10)]},
];
